import Head from 'next/head';

const Scoreboard = () => (
  <div>
    <Head>
      <title>Ranking | Covid Scoreboard</title>
      <meta name="description" content="Generated by create next app" />
    </Head>

    <main>
      <h1>Scoreboard</h1>
    </main>
  </div>
);

export default Scoreboard;
