import React from 'react';
import Head from 'next/head';
import { GetServerSideProps } from 'next';
import { ICountry } from '../../../@types/ICountry';
import { Header, Breadcrumbs, Table } from '../../../components';

interface ICountryIndex {
  country: ICountry
}

const CountryPage = ({ country }: ICountryIndex) => (
  <div>
    <Head>
      <title>{country.location} | Covid Scoreboard</title>
      <meta name="description" content="Generated by create next app" />
    </Head>
      <Header title={country?.location || ''} />
    <Breadcrumbs pages={[
      {
        name: 'Countries',
        href: '/countries',
        current: false
      },
      {
        name: country.location || '',
        href: `/countries/${country.slug}`,
        current: true
      }
    ]} />
  </div>
);

export const getServerSideProps: GetServerSideProps = async (context) => {
  const countrySlug = context?.params?.id;
  const res = await fetch(`${process.env.NEXT_PUBLIC_API_HOST}/api/countries/${countrySlug}`);
  const data = await res.json();
  let country: ICountry | null = data;

  return { props: { country } };
};

export default CountryPage;
