import React from 'react';
import Head from 'next/head';
import { GetServerSideProps } from 'next';
import { ICountry } from '../../../@types/ICountry';

interface ICountryIndex {
  country: ICountry
}

interface IPaths {
  params: {
    id: string
  }
}

const CountryPage = ({ country }: ICountryIndex) => (
  <div>
    <Head>
      <title>{country.location} | Covid Scoreboard</title>
      <meta name="description" content="Generated by create next app" />
    </Head>
    <h1>{country.location}</h1>
  </div>
);

export const getServerSideProps: GetServerSideProps = async (context) => {
  const countrySlug = context?.params?.id;
  const res = await fetch(`${process.env.NEXT_PUBLIC_API_HOST}/api/countries/${countrySlug}`);
  const data = await res.json();
  let country: ICountry | null = data;

  return { props: { country } };
};

export default CountryPage;
